#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
      path: /api/login_check
      methods: ['POST']

#register:
#    path: /register
#    controller: App\Controller\AuthController::register
#    methods: ['POST']
#
#apii:
#    path: /apii
#    controller: App\Controller\AuthController::apii
#    methods: ['POST']

#movies:
#  resource: App\Controller\Api\MovieController
#  prefix: api
#
#users:
#  resource: App\Controller\Api\UserController
#  prefix: api
#
#genres:
#  resource: App\Controller\Api\GenreController
#  prefix: api

pageNotFound:
    path:  /{path}
    defaults:
      {
        _controller: App\Controller\PageNotFoundController::pageNotFoundAction,
        path: ''
      }
    requirements:
        path: .*

#api:
#    prefix: /api
#    resource: '../src/Controller/Api'